### ISSUE TITLE
Allow reuse of ember-resolver package name.

### ISSUE THREAD

**Issue by rwjblue** [seeden/ember-require-resolver#2]
This package was originally registered on NPM as `ember-resolver` then subsequently changed to `ember-require-resolver`.  Would you mind adding me as an owner so that we can publish the official Ember CLI resolver ([ember-cli/ember-resolver](https://github.com/ember-cli/ember-resolver/)) as `ember-resolver` on NPM?

The command to run would be:

```
npm owner add rwjblue
```

I will make sure to publish the next version as a 2.0.0, and reference this package in its README as a back reference for those using the existing versions.

**Comment by seeden** [comment]
I am not the owner of the ember-resolver

**Comment by rwjblue** [comment]
I attempted to publish via `npm publish ember-resolver`, and it was already registered.

Looking at https://registry.npmjs.org/ember-resolver, it seems that you must have already unpublished?

**Comment by rwjblue** [comment]
Sorry for the troubles, looks like the issue was that I had to use a unique version number (since 1.0.0 was previously published).
